import test from 'node:test'
import assert from 'node:assert/strict'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const { AttendanceRuntimeService } = require('../../backend/attendance-runtime-v3/AttendanceRuntimeService.js')
const { createRuntimeApp } = require('../../backend/attendance-runtime-v3/app.js')
const { loadRuntimeConfig } = require('../../backend/attendance-runtime-v3/config.js')
const { assertPersistRecordAuthorized } = require('../../backend/attendance-runtime-v3/tenantPersistence.js')
const { WorkdayPersistenceService } = require('../../backend/services/attendance/WorkdayPersistenceService.js')

const TENANT = '69095bd5-fee5-4237-a1a4-186dd88310ff'; const EMPLOYEE = '6c94a683-1fbd-4427-af9e-8ea154ea50fa'; const REGISTRO = '5707fc4d-833a-48ab-bf49-90f5b30e0174'; const DEVICE = 'f693aea8-9f80-4e81-a99c-91b39e6d66d9'; const SCHEDULE = '5a753368-f019-4230-89e2-79beaa39ff0f'; const REVISION = '09df6a75-e231-4654-ae70-8448bdf2c312'; const WORKDAY = '5fe7ef34-7699-474b-b312-d0c5031a1fbe'; const TOKEN = 't'.repeat(32)
function client() { return { from(table) { const b = { select() { return this }, eq() { return this }, limit() { return this }, maybeSingle: async () => ({ data: table === 'registro_asistencia' ? { id: REGISTRO, cliente_id: TENANT, empleado_id: EMPLOYEE, dispositivo_id: DEVICE } : { cliente_id: TENANT }, error: null }) }; return b } } }
function auth(overrides = {}) { return { tenantId: TENANT, employeeId: EMPLOYEE, registroId: REGISTRO, scheduleId: SCHEDULE, operativeDate: '2026-09-09', ...overrides } }
function record(overrides = {}) { return { registro_id: REGISTRO, cliente_id: TENANT, empleado_id: EMPLOYEE, workday_date: '2026-09-09', schedule_id: SCHEDULE, timezone: 'America/Cancun', first_in: '2026-09-09T14:00:00.000Z', last_out: '2026-09-09T23:00:00.000Z', worked_minutes: 480, break_minutes: 60, overtime_minutes: 0, late_minutes: 0, early_leave_minutes: 0, status: 'COMPLETE', integrity_hash: 'e'.repeat(64), calculation_version: 3, ...overrides } }
function engine({ persistenceResult = 'UNCHANGED', mutation = null } = {}) { return (options) => ({ run: async () => { let persisted = null; if (options.persistenceMode === 'PERSIST') persisted = await options.persistenceService.persist(record(mutation || {})); return { registroId: REGISTRO, executionMode: 'ACTIVE', persistenceMode: options.persistenceMode, persistenceResult: persisted?.persistenceResult, workdayId: persisted?.workdayId, operativeDate: '2026-09-09', scheduleResolution: { kind: 'SCHEDULED', scheduleAssignmentId: '2984316c-1c93-4f66-853e-349f90b9f82c', scheduleRevisionId: REVISION, scheduleRevisionVersion: 1, scheduleRevisionHash: '77ee547cfef3de39f6b59e4d9f531d4c29f054cc2c72bb13018a911c2c274866' }, calculation: { clienteId: TENANT, empleadoId: EMPLOYEE, calculationVersion: 3 }, workdayRecord: record() } } }) }
function runtime(options = {}) { const persistenceResults = options.persistenceResults || ['UNCHANGED']; return new AttendanceRuntimeService({ client: client(), logger: { info() {}, error() {} }, featureLoader: async () => ({ mode: options.mode || 'ACTIVE' }), persistAuthorizationLoader: async () => options.authorization || auth(), persistenceServiceFactory: () => ({ persist: async () => ({ workdayId: WORKDAY, persistenceResult: persistenceResults.shift(), integrityHash: 'e'.repeat(64) }) }), orchestratorFactory: engine(options) }) }

test('ACTIVE READ_ONLY remains read-only while v3 PERSIST is explicit', async () => { const service = runtime(); const result = await service.executeActive({ registroId: REGISTRO }); assert.equal(result.persistence_mode, 'READ_ONLY'); assert.equal(result.persistenceCalls, 0); assert.equal(result.databaseWrites, 0); const persisted = await service.executePersist({ registroId: REGISTRO }); assert.equal(persisted.persistence_mode, 'PERSIST'); assert.equal(persisted.persistence_result, 'UNCHANGED'); assert.equal(persisted.databaseWrites, 0); assert.equal(persisted.persistenceCalls, 1) })
test('SHADOW and non-ACTIVE tenants cannot persist', async () => { await assert.rejects(() => runtime({ mode: 'SHADOW' }).executePersist({ registroId: REGISTRO }), { code: 'RUNTIME_RESOLUTION_MODE_MISMATCH' }); await assert.rejects(() => runtime().executeShadow({ registroId: REGISTRO }), { code: 'RUNTIME_SHADOW_WRITE_DENIED' }) })
test('missing persistence authorization fails closed before the engine', async () => { const service = runtime(); service.persistAuthorizationLoader = async () => { const e = new Error('denied'); e.code = 'PERSIST_AUTHORIZATION_DENIED'; throw e }; await assert.rejects(() => service.executePersist({ registroId: REGISTRO }), { code: 'PERSIST_AUTHORIZATION_DENIED' }) })
test('authorization is tenant and identity scoped', () => { assert.throws(() => assertPersistRecordAuthorized(record({ cliente_id: 'other-tenant' }), auth()), { code: 'PERSIST_AUTHORIZATION_SCOPE_MISMATCH' }); assert.throws(() => assertPersistRecordAuthorized(record({ schedule_id: 'other-schedule' }), auth()), { code: 'PERSIST_AUTHORIZATION_SCOPE_MISMATCH' }); assert.throws(() => assertPersistRecordAuthorized(record({ calculation_version: 2 }), auth()), { code: 'PERSIST_AUTHORIZATION_SCOPE_MISMATCH' }) })
test('isolated INSERTED then exact replay UNCHANGED are both accepted', async () => { const service = runtime({ persistenceResults: ['INSERTED', 'UNCHANGED'] }); const first = await service.executePersist({ registroId: REGISTRO }); const second = await service.executePersist({ registroId: REGISTRO }); assert.equal(first.persistence_result, 'INSERTED'); assert.equal(first.databaseWrites, 1); assert.equal(second.persistence_result, 'UNCHANGED'); assert.equal(second.databaseWrites, 0); assert.equal(first.workday_id, second.workday_id) })
test('existing production-shaped canary is UNCHANGED on every replay', async () => { const service = runtime({ persistenceResults: ['UNCHANGED', 'UNCHANGED'] }); const [a, b] = [await service.executePersist({ registroId: REGISTRO }), await service.executePersist({ registroId: REGISTRO })]; assert.deepEqual([a.persistence_result, b.persistence_result], ['UNCHANGED', 'UNCHANGED']); assert.equal(a.workday_id, WORKDAY); assert.equal(b.workday_id, WORKDAY) })
test('revision mismatch and assignment ambiguity fail through the engine before persistence', async () => { for (const code of ['SCHEDULE_REVISION_HASH_MISMATCH', 'AMBIGUOUS_SCHEDULE']) { const service = runtime(); service.orchestratorFactory = () => ({ run: async () => { const e = new Error(code); e.code = code; throw e } }); await assert.rejects(() => service.executePersist({ registroId: REGISTRO }), { code }) } })
test('v3 exposes PERSIST only under ACTIVE_PERSIST_CAPABLE and v2 capability is rejected by config', () => { const env = { SUPABASE_URL: 'https://project.example', SUPABASE_SECRET_KEY: 's'.repeat(20), ATTENDANCE_RUNTIME_INTERNAL_TOKEN: TOKEN, RUNTIME_VERSION: 'attendance-runtime-v3', BUILD_SHA: 'abcdef1', ATTENDANCE_RUNTIME_CAPABILITY: 'ACTIVE_PERSIST_CAPABLE' }; assert.equal(loadRuntimeConfig(env).runtimeCapability, 'ACTIVE_PERSIST_CAPABLE'); assert.throws(() => require('../../backend/attendance-runtime-v3/server.js').start({ ...env, ATTENDANCE_RUNTIME_CAPABILITY: 'ACTIVE_CAPABLE' }), /RUNTIME_PERSIST_CAPABILITY_REQUIRED/) })
test('PERSIST runtime route is authenticated and never accepts tenant authority from request', async () => { const service = runtime(); const app = createRuntimeApp({ service, config: { runtimeVersion: 'attendance-runtime-v3', buildSha: 'test', internalToken: TOKEN, runtimeCapability: 'ACTIVE_PERSIST_CAPABLE' }, readinessProbe: async () => {} }); const server = await new Promise((resolve) => { const s = app.listen(0, '127.0.0.1', () => resolve(s)) }); try { const url = `http://127.0.0.1:${server.address().port}`; assert.equal((await fetch(`${url}/internal/attendance/persist`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ registro_id: REGISTRO }) })).status, 401); assert.equal((await fetch(`${url}/internal/attendance/persist`, { method: 'POST', headers: { authorization: `Bearer ${TOKEN}`, 'content-type': 'application/json' }, body: JSON.stringify({ registro_id: REGISTRO, cliente_id: TENANT }) })).status, 400) } finally { await new Promise((resolve) => server.close(resolve)) } })
test('persistence boundary permits only INSERTED or UNCHANGED RPC responses', async () => { const payload = record(); const rpc = { rpc: async () => ({ data: [{ workday_id: WORKDAY, persistence_result: 'UNCHANGED', integrity_hash: payload.integrity_hash }], error: null }) }; assert.equal((await new WorkdayPersistenceService(rpc).persist(payload)).persistenceResult, 'UNCHANGED'); await assert.rejects(() => new WorkdayPersistenceService({ rpc: async () => ({ data: [{ workday_id: WORKDAY, persistence_result: 'UPDATED' }], error: null }) }).persist(payload), { code: 'WORKDAY_PERSISTENCE_RESPONSE_INVALID' }) })
