import test from 'node:test'
import assert from 'node:assert/strict'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const { AttendancePersistDispatcher, validateRuntimeResult } = require('../../backend/attendance-persist-dispatcher/dispatcher.js')
const { loadPersistAuthorization, PERSIST_FEATURE_KEY, PERSIST_FEATURE_MODE } = require('../../backend/attendance-runtime-v3/tenantPersistence.js')
const TENANT = '69095bd5-fee5-4237-a1a4-186dd88310ff'; const OTHER = '79095bd5-fee5-4237-a1a4-186dd88310ff'; const EMPLOYEE = '6c94a683-1fbd-4427-af9e-8ea154ea50fa'; const REGISTRO = '5707fc4d-833a-48ab-bf49-90f5b30e0174'; const EVENT = 'fcc67f56-d0ae-44c7-8b6e-1957420e8ccb'; const WORKDAY = '5fe7ef34-7699-474b-b312-d0c5031a1fbe'
const row = { outbox_id: 'a707fc4d-833a-48ab-bf49-90f5b30e0174', registro_id: REGISTRO, cliente_id: TENANT, empleado_id: EMPLOYEE, source_event_id: EVENT, attempt_count: 1 }
const runtimeResult = { registro_id: REGISTRO, tenant_id: TENANT, employee_id: EMPLOYEE, operative_date: '2026-09-09', assignment_id: '2984316c-1c93-4f66-853e-349f90b9f82c', schedule_revision_id: '09df6a75-e231-4654-ae70-8448bdf2c312', execution_mode: 'ACTIVE', persistence_mode: 'PERSIST', persistence_result: 'INSERTED', workday_id: WORKDAY, runtime_capability: 'ACTIVE_PERSIST_CAPABLE', engine_version: 'ATTENDANCE_ENGINE_V3', calculation_version: 3, databaseWrites: 1, persistenceCalls: 1, rpcWriteCalls: 1 }
function query(data) { return { select() { return this }, eq() { return this }, maybeSingle: async () => ({ data, error: null }) } }
function authorizationClient({ auth = { cliente_id: TENANT, feature_key: PERSIST_FEATURE_KEY, mode: PERSIST_FEATURE_MODE, enabled: true, canary_registro_id: null, canary_empleado_id: null, canary_schedule_id: null, canary_workday_date: null }, source = { id: EVENT, cliente_id: TENANT, employee_id: EMPLOYEE, source_type: 'ZKTECO', processing_status: 'PROCESSED' } } = {}) { return { from(table) { return query(table === 'tenant_features' ? auth : source) } } }
function dispatcher({ response = runtimeResult, status = 200, claimRows = [row], calls = [] } = {}) { const client = { rpc: async (name, params) => { calls.push([name, params]); return name === 'claim_attendance_persist_outbox' ? { data: claimRows, error: null } : { data: null, error: null } } }; return new AttendancePersistDispatcher({ client, config: { runtimeUrl: 'https://runtime.example', internalToken: 'x'.repeat(32), workerId: 'worker-v1', batchSize: 10 }, identityTokenProvider: async () => 'identity-token', fetchImpl: async () => ({ ok: status === 200, status, json: async () => response }), logger: { info() {}, error() {} } }) }

test('productive feature is explicit, tenant-scoped, revocable and requires a processed physical source event', async () => { const granted = await loadPersistAuthorization(authorizationClient(), { tenantId: TENANT, employeeId: EMPLOYEE, registroId: REGISTRO, sourceEventId: EVENT }); assert.equal(granted.tenantId, TENANT); await assert.rejects(() => loadPersistAuthorization(authorizationClient({ auth: null }), { tenantId: TENANT, employeeId: EMPLOYEE, registroId: REGISTRO, sourceEventId: EVENT }), { code: 'PERSIST_AUTHORIZATION_DENIED' }); await assert.rejects(() => loadPersistAuthorization(authorizationClient({ source: { id: EVENT, cliente_id: OTHER, employee_id: EMPLOYEE, source_type: 'ZKTECO', processing_status: 'PROCESSED' } }), { tenantId: TENANT, employeeId: EMPLOYEE, registroId: REGISTRO, sourceEventId: EVENT }), { code: 'PERSIST_SOURCE_EVENT_DENIED' }) })
test('worker sends only registro_id and acknowledges INSERTED; exact replay is accepted as UNCHANGED', async () => { const calls = []; const first = dispatcher({ calls }); const firstOutcomes = await first.runOnce(); assert.equal(firstOutcomes[0].status, 'SUCCEEDED'); assert.equal(calls[1][0], 'complete_attendance_persist_outbox'); assert.equal(calls[1][1].p_runtime_result, 'INSERTED'); const replay = dispatcher({ response: { ...runtimeResult, persistence_result: 'UNCHANGED', databaseWrites: 0 }, calls: [] }); assert.equal((await replay.runOnce())[0].persistence_result, 'UNCHANGED') })
test('multiple canonical registros may converge on one logical workday without authorizing a duplicate identity', () => { const second = { ...row, outbox_id: 'b707fc4d-833a-48ab-bf49-90f5b30e0174', registro_id: '6707fc4d-833a-48ab-bf49-90f5b30e0174', source_event_id: 'dcc67f56-d0ae-44c7-8b6e-1957420e8ccb' }; const firstResult = validateRuntimeResult(row, runtimeResult); const secondResult = validateRuntimeResult(second, { ...runtimeResult, registro_id: second.registro_id, persistence_result: 'UNCHANGED', databaseWrites: 0 }); assert.equal(firstResult.workday_id, secondResult.workday_id) })
test('tenant or employee mismatch, malformed runtime response, and non-200 authorization denial fail closed', async () => { assert.throws(() => validateRuntimeResult({ ...row, cliente_id: OTHER }, runtimeResult), { code: 'PERSIST_RUNTIME_RESPONSE_INVALID' }); assert.throws(() => validateRuntimeResult(row, { ...runtimeResult, employee_id: OTHER }), { code: 'PERSIST_RUNTIME_RESPONSE_INVALID' }); const calls = []; const denied = dispatcher({ status: 422, response: { error_code: 'PERSIST_AUTHORIZATION_DENIED' }, calls }); assert.equal((await denied.runOnce())[0].status, 'DENIED'); assert.equal(calls[1][1].p_terminal_status, 'DENIED') })
test('runtime transport failure and a crash before ACK are replay-safe: the worker records RETRY and never manufactures a workday', async () => { const calls = []; const worker = dispatcher({ calls }); worker.fetch = async () => { throw Object.assign(new Error('network'), { code: 'NETWORK' }) }; assert.equal((await worker.runOnce())[0].status, 'RETRY'); assert.equal(calls[1][1].p_terminal_status, 'RETRY') })
test('contract SQL uses an outbox, immutable revision resolution, service_role-only RPCs, and no live schedule fallback', async () => { const fs = await import('node:fs/promises'); const sql = await fs.readFile(new URL('../../database/live-schema/92_productive_persist_outbox_contract_change.sql', import.meta.url), 'utf8'); const rpc = sql.slice(sql.indexOf('CREATE OR REPLACE FUNCTION public.upsert_workday_record'), sql.lastIndexOf('REVOKE ALL ON FUNCTION public.upsert_workday_record')); assert.match(sql, /attendance_persist_outbox/); assert.match(sql, /WORKDAY_PERSIST_ACTIVE/); assert.match(sql, /PERSIST_ACTIVE/); assert.match(rpc, /schedule_revisions/); assert.doesNotMatch(rpc, /public\.horarios/i); assert.match(rpc, /ON CONFLICT\(cliente_id,empleado_id,workday_date\) DO NOTHING/); assert.match(sql, /REVOKE ALL ON FUNCTION public\.claim_attendance_persist_outbox[\s\S]*anon,authenticated/); assert.match(sql, /GRANT EXECUTE[\s\S]*TO service_role/); assert.doesNotMatch(sql, /http:|https:/i) })
