-- Phase 86: sole temporary authorization opening. It changes only tenant_features.
BEGIN ISOLATION LEVEL SERIALIZABLE;
LOCK TABLE public.tenant_features IN SHARE ROW EXCLUSIVE MODE;
LOCK TABLE public.registro_asistencia,public.empleados_horarios,public.schedule_revisions,public.workday_records,public.workday_record_history IN SHARE MODE;
DO $authorize_persist$
DECLARE v_rows bigint; v_tenant uuid := '69095bd5-fee5-4237-a1a4-186dd88310ff'; v_employee uuid := '6c94a683-1fbd-4427-af9e-8ea154ea50fa'; v_registro uuid := '5707fc4d-833a-48ab-bf49-90f5b30e0174'; v_assignment uuid := '2984316c-1c93-4f66-853e-349f90b9f82c'; v_schedule uuid := '5a753368-f019-4230-89e2-79beaa39ff0f'; v_revision uuid := '09df6a75-e231-4654-ae70-8448bdf2c312'; v_workday uuid := '5fe7ef34-7699-474b-b312-d0c5031a1fbe'; v_date date := '2026-09-09'; v_revision_hash text := '77ee547cfef3de39f6b59e4d9f531d4c29f054cc2c72bb13018a911c2c274866'; v_workday_hash text := 'ec6d5100a838e87181c9c410bb3011cfbfe12349468db9517753d094cc086d49';
BEGIN
 IF (SELECT count(*) FROM public.tenant_features WHERE feature_key='REVISION_SCHEDULE_RESOLVER' AND mode='ACTIVE' AND enabled IS TRUE)<>1 OR (SELECT count(*) FROM public.tenant_features WHERE cliente_id=v_tenant AND feature_key='REVISION_SCHEDULE_RESOLVER' AND mode='ACTIVE' AND enabled IS TRUE)<>1 THEN RAISE EXCEPTION 'PERSIST_AUTH_ACTIVE_RESOLVER_INVALID'; END IF;
 IF (SELECT count(*) FROM public.tenant_features WHERE feature_key='WORKDAY_PERSIST_CANARY')<>0 THEN RAISE EXCEPTION 'PERSIST_AUTH_ALREADY_EXISTS'; END IF;
 IF (SELECT count(*) FROM public.registro_asistencia WHERE id=v_registro AND cliente_id=v_tenant AND empleado_id=v_employee AND xmin::text='16338')<>1 THEN RAISE EXCEPTION 'PERSIST_AUTH_CANARY_IDENTITY_INVALID'; END IF;
 IF (SELECT count(*) FROM public.empleados_horarios WHERE cliente_id=v_tenant AND empleado_id=v_employee AND activo IS TRUE AND fecha_inicio<=v_date AND (fecha_fin IS NULL OR fecha_fin>=v_date))<>1 OR NOT EXISTS(SELECT 1 FROM public.empleados_horarios WHERE id=v_assignment AND cliente_id=v_tenant AND empleado_id=v_employee AND horario_id=v_schedule AND schedule_revision_id=v_revision) THEN RAISE EXCEPTION 'PERSIST_AUTH_ASSIGNMENT_INVALID'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.schedule_revisions WHERE id=v_revision AND cliente_id=v_tenant AND horario_id=v_schedule AND version=1 AND integrity_hash=v_revision_hash AND public.schedule_revision_calculation_hash(config_snapshot)=v_revision_hash) THEN RAISE EXCEPTION 'PERSIST_AUTH_REVISION_INVALID'; END IF;
 IF (SELECT count(*) FROM public.workday_records WHERE cliente_id=v_tenant AND empleado_id=v_employee AND workday_date=v_date)<>1 OR NOT EXISTS(SELECT 1 FROM public.workday_records WHERE id=v_workday AND integrity_hash=v_workday_hash AND calculation_version=3) OR (SELECT count(*) FROM public.workday_record_history WHERE cliente_id=v_tenant AND empleado_id=v_employee AND workday_date=v_date)<>1 OR NOT EXISTS(SELECT 1 FROM public.workday_record_history WHERE workday_record_id=v_workday AND integrity_hash=v_workday_hash AND calculation_version=3 AND action='INSERTED') THEN RAISE EXCEPTION 'PERSIST_AUTH_EXISTING_EVIDENCE_INVALID'; END IF;
 IF (SELECT md5(COALESCE(string_agg(concat_ws('|',id::text,cliente_id::text,empleado_id::text,workday_date::text,schedule_id::text,integrity_hash,calculation_version::text),'|' ORDER BY id::text),'')) FROM public.workday_records WHERE cliente_id=v_tenant AND empleado_id=v_employee AND workday_date=v_date)<>'668e4ccfa75a027b5fcc47d4963a06d1' OR (SELECT md5(COALESCE(string_agg(concat_ws('|',workday_record_id::text,cliente_id::text,empleado_id::text,workday_date::text,integrity_hash,calculation_version::text,action),'|' ORDER BY id::text),'')) FROM public.workday_record_history WHERE cliente_id=v_tenant AND empleado_id=v_employee AND workday_date=v_date)<>'0f87f945e84a9747e5bc275660bc7c0a' THEN RAISE EXCEPTION 'PERSIST_AUTH_FINGERPRINT_INVALID'; END IF;
 INSERT INTO public.tenant_features(cliente_id,feature_key,mode,enabled,canary_registro_id,canary_empleado_id,canary_schedule_id,canary_workday_date) VALUES(v_tenant,'WORKDAY_PERSIST_CANARY','PERSIST_CANARY',true,v_registro,v_employee,v_schedule,v_date);
 GET DIAGNOSTICS v_rows = ROW_COUNT; IF v_rows<>1 THEN RAISE EXCEPTION 'PERSIST_AUTH_AFFECTED_ROWS_INVALID: %',v_rows; END IF;
END $authorize_persist$;
COMMIT;
