-- Phase 88: read-only proof that the second exact runtime-v3 PERSIST is also UNCHANGED.
BEGIN TRANSACTION READ ONLY;
WITH supplied AS (SELECT /* PERSIST_V3_REPLAY_RESPONSE */ NULL::jsonb AS response), e AS (SELECT '69095bd5-fee5-4237-a1a4-186dd88310ff'::uuid tenant_id,'6c94a683-1fbd-4427-af9e-8ea154ea50fa'::uuid employee_id,'5707fc4d-833a-48ab-bf49-90f5b30e0174'::uuid registro_id,'5fe7ef34-7699-474b-b312-d0c5031a1fbe'::uuid workday_id,'2026-09-09'::date operative_date,'ec6d5100a838e87181c9c410bb3011cfbfe12349468db9517753d094cc086d49'::text workday_hash), checks AS (
 SELECT jsonb_build_object(
  'runtime_replay_unchanged',s.response->>'persistence_result'='UNCHANGED' AND s.response->>'workday_id'=e.workday_id::text AND s.response->>'execution_mode'='ACTIVE' AND s.response->>'persistence_mode'='PERSIST' AND COALESCE((s.response->>'databaseWrites')::integer,-1)=0 AND COALESCE((s.response->>'persistenceCalls')::integer,-1)=1,
  'logical_identity_unique',(SELECT count(*) FROM public.workday_records w WHERE w.cliente_id=e.tenant_id AND w.empleado_id=e.employee_id AND w.workday_date=e.operative_date)=1 AND (SELECT count(*) FROM public.workday_record_history h WHERE h.cliente_id=e.tenant_id AND h.empleado_id=e.employee_id AND h.workday_date=e.operative_date)=1,
  'same_snapshot',EXISTS(SELECT 1 FROM public.workday_records w WHERE w.id=e.workday_id AND w.integrity_hash=e.workday_hash AND w.calculation_version=3) AND EXISTS(SELECT 1 FROM public.workday_record_history h WHERE h.workday_record_id=e.workday_id AND h.integrity_hash=e.workday_hash AND h.calculation_version=3 AND h.action='INSERTED'),
  'fingerprints_intact',(SELECT md5(COALESCE(string_agg(concat_ws('|',w.id::text,w.cliente_id::text,w.empleado_id::text,w.workday_date::text,w.schedule_id::text,w.integrity_hash,w.calculation_version::text),'|' ORDER BY w.id::text),'')) FROM public.workday_records w WHERE w.cliente_id=e.tenant_id AND w.empleado_id=e.employee_id AND w.workday_date=e.operative_date)='668e4ccfa75a027b5fcc47d4963a06d1' AND (SELECT md5(COALESCE(string_agg(concat_ws('|',h.workday_record_id::text,h.cliente_id::text,h.empleado_id::text,h.workday_date::text,h.integrity_hash,h.calculation_version::text,h.action),'|' ORDER BY h.id::text),'')) FROM public.workday_record_history h WHERE h.cliente_id=e.tenant_id AND h.empleado_id=e.employee_id AND h.workday_date=e.operative_date)='0f87f945e84a9747e5bc275660bc7c0a'
 ) value FROM supplied s CROSS JOIN e), failed AS (SELECT COALESCE(jsonb_agg(key ORDER BY key) FILTER (WHERE value='false'),'[]'::jsonb) value FROM checks CROSS JOIN LATERAL jsonb_each_text(checks.value))
SELECT jsonb_build_object('phase','88_persistence_replay_postcheck','read_only',current_setting('transaction_read_only'),'checks',checks.value,'failed_checks',failed.value,'persistence_replay_postcheck_pass',current_setting('transaction_read_only')='on' AND failed.value='[]'::jsonb) FROM checks CROSS JOIN failed;
ROLLBACK;
