-- Phase 89: read-only final proof before retiring only the temporary canary authorization.
BEGIN TRANSACTION READ ONLY;
WITH e AS (SELECT '69095bd5-fee5-4237-a1a4-186dd88310ff'::uuid tenant_id,'6c94a683-1fbd-4427-af9e-8ea154ea50fa'::uuid employee_id,'5707fc4d-833a-48ab-bf49-90f5b30e0174'::uuid registro_id,'2984316c-1c93-4f66-853e-349f90b9f82c'::uuid assignment_id,'5a753368-f019-4230-89e2-79beaa39ff0f'::uuid schedule_id,'09df6a75-e231-4654-ae70-8448bdf2c312'::uuid revision_id,'5fe7ef34-7699-474b-b312-d0c5031a1fbe'::uuid workday_id,'2026-09-09'::date operative_date,'77ee547cfef3de39f6b59e4d9f531d4c29f054cc2c72bb13018a911c2c274866'::text revision_hash,'ec6d5100a838e87181c9c410bb3011cfbfe12349468db9517753d094cc086d49'::text workday_hash,'16338'::text registro_xmin,'a66376e83b8162084b2219d17ebdaadd'::text rpc_hash), checks AS (
 SELECT jsonb_build_object(
  'pilot_active_exactly_one',(SELECT count(*) FROM public.tenant_features f WHERE f.cliente_id=e.tenant_id AND f.feature_key='REVISION_SCHEDULE_RESOLVER' AND f.mode='ACTIVE' AND f.enabled IS TRUE)=1 AND (SELECT count(*) FROM public.tenant_features WHERE feature_key='REVISION_SCHEDULE_RESOLVER' AND mode='ACTIVE' AND enabled IS TRUE)=1,
  'authorization_only_pilot',(SELECT count(*) FROM public.tenant_features WHERE feature_key='WORKDAY_PERSIST_CANARY')=1 AND (SELECT count(*) FROM public.tenant_features f WHERE f.cliente_id=e.tenant_id AND f.feature_key='WORKDAY_PERSIST_CANARY' AND f.mode='PERSIST_CANARY' AND f.enabled IS TRUE AND f.canary_registro_id=e.registro_id AND f.canary_empleado_id=e.employee_id AND f.canary_schedule_id=e.schedule_id AND f.canary_workday_date=e.operative_date)=1,
  'canary_xmin_intact',(SELECT count(*) FROM public.registro_asistencia r WHERE r.id=e.registro_id AND r.cliente_id=e.tenant_id AND r.empleado_id=e.employee_id AND r.xmin::text=e.registro_xmin)=1,
  'revision_only_exact',EXISTS(SELECT 1 FROM public.empleados_horarios eh JOIN public.schedule_revisions sr ON sr.id=eh.schedule_revision_id AND sr.cliente_id=eh.cliente_id WHERE eh.id=e.assignment_id AND eh.cliente_id=e.tenant_id AND eh.empleado_id=e.employee_id AND eh.horario_id=e.schedule_id AND eh.schedule_revision_id=e.revision_id AND sr.version=1 AND sr.integrity_hash=e.revision_hash AND public.schedule_revision_calculation_hash(sr.config_snapshot)=e.revision_hash),
  'workday_integrity_unique',(SELECT count(*) FROM public.workday_records w WHERE w.cliente_id=e.tenant_id AND w.empleado_id=e.employee_id AND w.workday_date=e.operative_date)=1 AND EXISTS(SELECT 1 FROM public.workday_records w WHERE w.id=e.workday_id AND w.integrity_hash=e.workday_hash AND w.calculation_version=3),
  'history_immutable',(SELECT count(*) FROM public.workday_record_history h WHERE h.cliente_id=e.tenant_id AND h.empleado_id=e.employee_id AND h.workday_date=e.operative_date)=1 AND EXISTS(SELECT 1 FROM public.workday_record_history h WHERE h.workday_record_id=e.workday_id AND h.integrity_hash=e.workday_hash AND h.calculation_version=3 AND h.action='INSERTED') AND NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.upsert_workday_record(uuid,uuid,date,uuid,text,timestamp with time zone,timestamp with time zone,integer,integer,integer,integer,integer,text,text,integer,uuid)') AND lower(pg_get_functiondef(p.oid)) LIKE '%update public.workday_records%'),
  'fingerprints_intact',(SELECT md5(COALESCE(string_agg(concat_ws('|',w.id::text,w.cliente_id::text,w.empleado_id::text,w.workday_date::text,w.schedule_id::text,w.integrity_hash,w.calculation_version::text),'|' ORDER BY w.id::text),'')) FROM public.workday_records w WHERE w.cliente_id=e.tenant_id AND w.empleado_id=e.employee_id AND w.workday_date=e.operative_date)='668e4ccfa75a027b5fcc47d4963a06d1' AND (SELECT md5(COALESCE(string_agg(concat_ws('|',h.workday_record_id::text,h.cliente_id::text,h.empleado_id::text,h.workday_date::text,h.integrity_hash,h.calculation_version::text,h.action),'|' ORDER BY h.id::text),'')) FROM public.workday_record_history h WHERE h.cliente_id=e.tenant_id AND h.empleado_id=e.employee_id AND h.workday_date=e.operative_date)='0f87f945e84a9747e5bc275660bc7c0a',
  'rpc_fingerprint_exact',(SELECT md5(pg_get_functiondef(p.oid)) FROM pg_proc p WHERE p.oid=to_regprocedure('public.upsert_workday_record(uuid,uuid,date,uuid,text,timestamp with time zone,timestamp with time zone,integer,integer,integer,integer,integer,text,text,integer,uuid)'))=e.rpc_hash
 ) value FROM e), failed AS (SELECT COALESCE(jsonb_agg(key ORDER BY key) FILTER (WHERE value='false'),'[]'::jsonb) value FROM checks CROSS JOIN LATERAL jsonb_each_text(checks.value))
SELECT jsonb_build_object('phase','89_persistence_production_final_postcheck','read_only',current_setting('transaction_read_only'),'runtime_v3_external_gate_required',true,'checks',checks.value,'failed_checks',failed.value,'persistence_production_final_postcheck_pass',current_setting('transaction_read_only')='on' AND failed.value='[]'::jsonb) FROM checks CROSS JOIN failed;
ROLLBACK;
